"""Database plumbing that can be verified without a running server."""

from __future__ import annotations

from sqlalchemy import Engine

from indian_equity_research.config import Settings
from indian_equity_research.database.base import NAMING_CONVENTION, Base, metadata
from indian_equity_research.database.connection import (
    create_database_engine,
    create_session_factory,
    dispose_engine,
)
from indian_equity_research.database.health import check_database_health
from tests.conftest import SettingsFactory

SECRET = "engine-level-secret"


class TestDeclarativeBase:
    def test_base_uses_the_shared_metadata(self) -> None:
        assert Base.metadata is metadata

    def test_naming_convention_is_alembic_ready(self) -> None:
        """Named constraints are what make autogenerated migrations reversible."""
        assert metadata.naming_convention == NAMING_CONVENTION
        for key in ("ix", "uq", "ck", "fk", "pk"):
            assert key in metadata.naming_convention

    def test_no_tables_are_defined_in_this_phase(self) -> None:
        """Phase 1 defines no financial-data tables. This guards that boundary."""
        assert metadata.tables == {}


class TestEngineCreation:
    def test_creates_an_engine_without_connecting(self, make_settings: SettingsFactory) -> None:
        settings = make_settings(database_password=SECRET)
        engine = create_database_engine(settings)
        try:
            assert isinstance(engine, Engine)
            assert engine.dialect.name == "postgresql"
        finally:
            dispose_engine(engine)

    def test_engine_repr_does_not_leak_the_password(self, make_settings: SettingsFactory) -> None:
        settings = make_settings(database_password=SECRET)
        engine = create_database_engine(settings)
        try:
            assert SECRET not in repr(engine)
            assert SECRET not in str(engine.url)
        finally:
            dispose_engine(engine)

    def test_session_factory_is_bound_to_the_engine(self, make_settings: SettingsFactory) -> None:
        engine = create_database_engine(make_settings())
        try:
            assert create_session_factory(engine).kw["bind"] is engine
        finally:
            dispose_engine(engine)

    def test_dispose_is_safe_to_call_twice(self, make_settings: SettingsFactory) -> None:
        engine = create_database_engine(make_settings())
        dispose_engine(engine)
        dispose_engine(engine)


class TestHealthCheckFailurePath:
    def test_reports_failure_without_raising(self, unreachable_settings: Settings) -> None:
        health = check_database_health(unreachable_settings)
        assert health.is_healthy is False
        assert health.error
        assert health.latency_ms is None
        assert health.server_version is None

    def test_failure_description_is_readable(self, unreachable_settings: Settings) -> None:
        assert check_database_health(unreachable_settings).describe().startswith("FAIL")

    def test_failure_never_exposes_the_password(self, make_settings: SettingsFactory) -> None:
        settings = make_settings(
            database_host="127.0.0.1",
            database_port=1,
            database_password=SECRET,
            database_ssl_mode="disable",
            database_connect_timeout_seconds=1,
        )
        health = check_database_health(settings)
        assert health.is_healthy is False
        assert SECRET not in (health.error or "")
        assert SECRET not in health.target
        assert SECRET not in health.describe()
